/**
 * Error Code Documentation Generator
 *
 * Produces a stable, readable markdown table from the SDK's canonical
 * error registry (`core/error-codes.ts`'s `ERROR_CODE_REGISTRY`) plus
 * the set of error codes actually referenced by the `*ErrorCode` const
 * objects in `core/errors.ts` (`ContractErrorCode`, `WalletErrorCode`,
 * `ReconciliationErrorCode`).
 *
 * Cross-referencing both sources lets `findUndocumentedErrorCodes`
 * catch the case the issue calls out explicitly: a new error code
 * added to one of the `*ErrorCode` objects without a matching
 * `ERROR_CODE_REGISTRY` entry (would otherwise ship silently
 * undocumented).
 */
import { ERROR_CODE_REGISTRY, type ErrorCodeEntry } from "../core/error-codes";
import { ContractErrorCode, ReconciliationErrorCode, WalletErrorCode } from "../core/errors";

/** All error codes declared by the SDK's `*ErrorCode` const objects, by source. */
export function getDeclaredErrorCodesBySource(): Record<string, string[]> {
  return {
    ContractErrorCode: Object.values(ContractErrorCode),
    WalletErrorCode: Object.values(WalletErrorCode),
    ReconciliationErrorCode: Object.values(ReconciliationErrorCode),
  };
}

/**
 * Returns declared error codes (from the `*ErrorCode` const objects)
 * that have no corresponding entry in `registry`.
 *
 * An empty result means every declared code is documented — this is
 * the check a CI script should run and fail on non-empty output.
 *
 * @param registry - Defaults to the real `ERROR_CODE_REGISTRY`;
 *   overridable so tests can simulate an undocumented code without
 *   mutating the module-level registry.
 */
export function findUndocumentedErrorCodes(
  registry: Record<string, ErrorCodeEntry> = ERROR_CODE_REGISTRY
): string[] {
  const declared = new Set(Object.values(getDeclaredErrorCodesBySource()).flat());
  return Array.from(declared)
    .filter((code) => !(code in registry))
    .sort();
}

interface ErrorDocRow {
  code: string;
  source: string;
  category: string;
  meaning: string;
  retryable: boolean;
  suggestedFix: string;
}

/** Builds the source label(s) for a registry code from the declared `*ErrorCode` objects. */
function findSourcesForCode(code: string, bySource: Record<string, string[]>): string[] {
  return Object.entries(bySource)
    .filter(([, codes]) => codes.includes(code))
    .map(([source]) => source);
}

function escapeMarkdownCell(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

/**
 * Builds the full set of documentation rows from `ERROR_CODE_REGISTRY`,
 * annotated with which `*ErrorCode` source(s) reference each code
 * (falling back to `"registry"` for codes not surfaced by any
 * `*ErrorCode` object, e.g. proof-input and audit codes thrown directly
 * by string literal).
 */
export function buildErrorDocRows(
  registry: Record<string, ErrorCodeEntry> = ERROR_CODE_REGISTRY
): ErrorDocRow[] {
  const bySource = getDeclaredErrorCodesBySource();

  return Object.entries(registry)
    .map(([code, entry]) => {
      const sources = findSourcesForCode(code, bySource);
      return {
        code,
        source: sources.length > 0 ? sources.join(", ") : "registry",
        category: entry.category,
        meaning: entry.meaning,
        retryable: entry.retryable,
        suggestedFix: entry.suggestedMessage,
      };
    })
    .sort((a, b) => a.code.localeCompare(b.code));
}

/**
 * Renders the given rows as a markdown document with a summary table.
 *
 * Output is deterministic (rows sorted by code) so repeated generation
 * against unchanged source produces byte-identical output — this is
 * what allows CI to diff-check the generated file for staleness.
 */
export function renderErrorDocsMarkdown(rows: ErrorDocRow[] = buildErrorDocRows()): string {
  const lines: string[] = [
    "# SDK Error Codes",
    "",
    "> Generated by `scripts/generate-error-docs.js` from `src/core/error-codes.ts`.",
    "> Do not edit this file by hand — regenerate it instead.",
    "",
    `${rows.length} documented error code(s).`,
    "",
    "| Code | Source | Category | Meaning | Retryable | Suggested Fix |",
    "| --- | --- | --- | --- | --- | --- |",
  ];

  for (const row of rows) {
    lines.push(
      `| \`${row.code}\` | ${row.source} | ${row.category} | ${escapeMarkdownCell(
        row.meaning
      )} | ${row.retryable ? "yes" : "no"} | ${escapeMarkdownCell(row.suggestedFix)} |`
    );
  }

  lines.push("");
  return lines.join("\n");
}
